In [1]:
import pandas as pd

In [2]:
# Read CSV
df = pd.read_csv("alzheimers_disease_data.csv")
df.head()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis,DoctorInCharge
0,4751,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,...,0,0,1.725883,0,0,0,1,0,0,XXXConfid
1,4752,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,...,0,0,2.592424,0,0,0,0,1,0,XXXConfid
2,4753,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,...,0,0,7.119548,0,1,0,1,0,0,XXXConfid
3,4754,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,...,0,1,6.481226,0,0,0,0,0,0,XXXConfid
4,4755,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,...,0,0,0.014691,0,0,1,1,0,0,XXXConfid

In [3]:
# Is there any null values?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PatientID                  2149 non-null   int64
 1   Age                        2149 non-null   int64
 2   Gender                     2149 non-null   int64
 3   Ethnicity                  2149 non-null   int64
 4   EducationLevel             2149 non-null   int64
 5   BMI                        2149 non-null   float64
 6   Smoking                    2149 non-null   int64
 7   AlcoholConsumption         2149 non-null   float64
 8   PhysicalActivity           2149 non-null   float64
 9   DietQuality                2149 non-null   float64
 10  SleepQuality               2149 non-null   float64
 11  FamilyHistoryAlzheimers    2149 non-null   int64
 12  CardiovascularDisease      2149 non-null   int64
 13  Diabetes                   2149 non-null   int64
 14  Depression                 2149 non-null   int64
 15  HeadInjury                 2149 non-null   int64
 16  Hypertension               2149 non-null   int64
 17  SystolicBP                 2149 non-null   int64
 18  DiastolicBP                2149 non-null   int64
 19  CholesterolTotal           2149 non-null   float64
 20  CholesterolLDL             2149 non-null   float64
 21  CholesterolHDL             2149 non-null   float64
 22  CholesterolTriglycerides   2149 non-null   float64
 23  MMSE                       2149 non-null   float64
 24  FunctionalAssessment       2149 non-null   float64
 25  MemoryComplaints           2149 non-null   int64
 26  BehavioralProblems         2149 non-null   int64
 27  ADL                        2149 non-null   float64
 28  Confusion                  2149 non-null   int64
 29  Disorientation             2149 non-null   int64
 30  PersonalityChanges         2149 non-null   int64
 31  DifficultyCompletingTasks  2149 non-null   int64
 32  Forgetfulness              2149 non-null   int64
 33  Diagnosis                  2149 non-null   int64
 34  DoctorInCharge             2149 non-null   object
dtypes: float64(12), int64(22), object(1)
memory usage: 587.7+ KB

In [4]:
# Drop Educational Level and Doc in Charge Columns. 
df = df.drop(columns=["EducationLevel", "DoctorInCharge"])

In [5]:
# Print Columns 
print(df.columns)

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'BMI', 'Smoking',
       'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'FamilyHistoryAlzheimers', 'CardiovascularDisease', 'Diabetes',
       'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP', 'DiastolicBP',
       'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment',
       'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion',
       'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks',
       'Forgetfulness', 'Diagnosis'],
      dtype='object')

In [6]:
# Export to a CSV
df.to_csv('../Resources/cleaned_alzheimers_disease_data.csv')

In [7]:
# Gender and Ethnicity Mapping to change into a categories for Tableau. 
gender_mapping = {0: 'Male', 1: 'Female'}
ethnicity_mapping = {0: 'Caucasian', 1: 'African American', 2: 'Asian', 3: 'Other'}

In [8]:
# Apply Gender Mapping 
df['Gender'] = df['Gender'].map(gender_mapping)

df.head(10)

,PatientID,Age,Gender,Ethnicity,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
0,4751,73,Male,0,22.927749,0,13.297218,6.327112,1.347214,9.025679,...,6.518877,0,0,1.725883,0,0,0,1,0,0
1,4752,89,Male,0,26.827681,0,4.542524,7.619885,0.518767,7.151293,...,7.118696,0,0,2.592424,0,0,0,0,1,0
2,4753,73,Male,3,17.795882,0,19.555085,7.844988,1.826335,9.673574,...,5.895077,0,0,7.119548,0,1,0,1,0,0
3,4754,74,Female,0,33.800817,1,12.209266,8.428001,7.435604,8.392554,...,8.965106,0,1,6.481226,0,0,0,0,0,0
4,4755,89,Male,0,20.716974,0,18.454356,6.310461,0.795498,5.597238,...,6.045039,0,0,0.014691,0,0,1,1,0,0
5,4756,86,Female,1,30.626886,0,4.140144,0.211062,1.584922,7.261953,...,5.510144,0,0,9.015686,1,0,0,0,0,0
6,4757,68,Male,3,38.387622,1,0.646047,9.257695,5.897388,5.477686,...,6.062124,0,0,9.236328,0,0,0,0,1,0
7,4758,75,Male,0,18.776009,0,13.723826,4.649451,8.341903,4.213210,...,3.401374,0,0,4.517248,1,0,0,0,1,1
8,4759,72,Female,1,27.833188,0,12.167848,1.531360,6.736882,5.748224,...,7.396061,0,1,0.756232,0,0,1,0,0,0
9,4760,87,Male,0,35.456302,1,16.028688,6.440773,8.086019,7.551773,...,1.148904,0,1,4.554394,0,0,0,0,0,0

In [9]:
# Apply Ethnicity Mapping
df["Ethnicity"] = df["Ethnicity"].map(ethnicity_mapping)

df.head(10)

,PatientID,Age,Gender,Ethnicity,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
0,4751,73,Male,Caucasian,22.927749,0,13.297218,6.327112,1.347214,9.025679,...,6.518877,0,0,1.725883,0,0,0,1,0,0
1,4752,89,Male,Caucasian,26.827681,0,4.542524,7.619885,0.518767,7.151293,...,7.118696,0,0,2.592424,0,0,0,0,1,0
2,4753,73,Male,Other,17.795882,0,19.555085,7.844988,1.826335,9.673574,...,5.895077,0,0,7.119548,0,1,0,1,0,0
3,4754,74,Female,Caucasian,33.800817,1,12.209266,8.428001,7.435604,8.392554,...,8.965106,0,1,6.481226,0,0,0,0,0,0
4,4755,89,Male,Caucasian,20.716974,0,18.454356,6.310461,0.795498,5.597238,...,6.045039,0,0,0.014691,0,0,1,1,0,0
5,4756,86,Female,African American,30.626886,0,4.140144,0.211062,1.584922,7.261953,...,5.510144,0,0,9.015686,1,0,0,0,0,0
6,4757,68,Male,Other,38.387622,1,0.646047,9.257695,5.897388,5.477686,...,6.062124,0,0,9.236328,0,0,0,0,1,0
7,4758,75,Male,Caucasian,18.776009,0,13.723826,4.649451,8.341903,4.213210,...,3.401374,0,0,4.517248,1,0,0,0,1,1
8,4759,72,Female,African American,27.833188,0,12.167848,1.531360,6.736882,5.748224,...,7.396061,0,1,0.756232,0,0,1,0,0,0
9,4760,87,Male,Caucasian,35.456302,1,16.028688,6.440773,8.086019,7.551773,...,1.148904,0,1,4.554394,0,0,0,0,0,0

In [10]:
# Print Columns
print(df.columns)

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'BMI', 'Smoking',
       'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'FamilyHistoryAlzheimers', 'CardiovascularDisease', 'Diabetes',
       'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP', 'DiastolicBP',
       'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment',
       'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion',
       'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks',
       'Forgetfulness', 'Diagnosis'],
      dtype='object')

In [11]:
# Drop additional Columns 
df = df.drop(columns=['SystolicBP', 'DiastolicBP',
       'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'MMSE', 'ADL'])

In [12]:
print(df.columns)

Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'BMI', 'Smoking',
       'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
       'FamilyHistoryAlzheimers', 'CardiovascularDisease', 'Diabetes',
       'Depression', 'HeadInjury', 'Hypertension', 'FunctionalAssessment',
       'MemoryComplaints', 'BehavioralProblems', 'Confusion', 'Disorientation',
       'PersonalityChanges', 'DifficultyCompletingTasks', 'Forgetfulness',
       'Diagnosis'],
      dtype='object')

In [13]:
# Export CSV for machine learning
df.to_csv('../Resources/cleaned_alzheimers_disease_data.csv')
df.head()

,PatientID,Age,Gender,Ethnicity,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,Hypertension,FunctionalAssessment,MemoryComplaints,BehavioralProblems,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
0,4751,73,Male,Caucasian,22.927749,0,13.297218,6.327112,1.347214,9.025679,...,0,6.518877,0,0,0,0,0,1,0,0
1,4752,89,Male,Caucasian,26.827681,0,4.542524,7.619885,0.518767,7.151293,...,0,7.118696,0,0,0,0,0,0,1,0
2,4753,73,Male,Other,17.795882,0,19.555085,7.844988,1.826335,9.673574,...,0,5.895077,0,0,0,1,0,1,0,0
3,4754,74,Female,Caucasian,33.800817,1,12.209266,8.428001,7.435604,8.392554,...,0,8.965106,0,1,0,0,0,0,0,0
4,4755,89,Male,Caucasian,20.716974,0,18.454356,6.310461,0.795498,5.597238,...,0,6.045039,0,0,0,0,1,1,0,0

In [14]:
# Additional mapping for Tableau
smoking_mapping = {0: 'No', 1: 'Yes'}
Hypertension_mapping = {0: 'No', 1: 'Yes'}
Memory_mapping = {0: 'No', 1: 'Yes'}
Behavioral_mapping = {0: 'No', 1: 'Yes'}
Confusion_mapping = {0: 'No', 1: 'Yes'}
Disorientation_mapping = {0: 'No', 1: 'Yes'}
Personality_mapping = {0: 'No', 1: 'Yes'}
Forgetfulness_mapping = {0: 'No', 1: 'Yes'}
Diagnosis_mapping = {0: 'No', 1: 'Yes'}
FamilyHistory_mapping = {0: 'No', 1: 'Yes'}
Cardio_mapping = {0: 'No', 1: 'Yes'}
Diabetes_mapping = {0: 'No', 1: 'Yes'}
HeadInjury_mapping = {0: 'No', 1: 'Yes'}
Task_mapping = {0: 'No', 1: 'Yes'}

In [15]:
# Apply mapping
df['Smoking'] = df['Smoking'].map(smoking_mapping) 
df['Hypertension'] = df['Hypertension'].map(Hypertension_mapping) 
df['MemoryComplaints'] = df['MemoryComplaints'].map(Memory_mapping)
df['BehavioralProblems'] = df['BehavioralProblems'].map(Behavioral_mapping) 
df['Confusion'] = df['Confusion'].map(Confusion_mapping) 
df['Disorientation'] = df['Disorientation'].map(Disorientation_mapping) 
df['PersonalityChanges'] = df['PersonalityChanges'].map(Personality_mapping) 
df['Forgetfulness'] = df['Forgetfulness'].map(Forgetfulness_mapping) 
df['Diagnosis'] = df['Diagnosis'].map(Diagnosis_mapping)
df['FamilyHistoryAlzheimers'] = df['FamilyHistoryAlzheimers'].map(FamilyHistory_mapping) 
df['CardiovascularDisease'] = df['CardiovascularDisease'].map(Cardio_mapping)
df['Diabetes'] = df['Diabetes'].map(Diabetes_mapping) 
df['HeadInjury'] = df['HeadInjury'].map(HeadInjury_mapping) 
df['DifficultyCompletingTasks'] = df['DifficultyCompletingTasks'].map(HeadInjury_mapping) 

df.head()

,PatientID,Age,Gender,Ethnicity,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,Hypertension,FunctionalAssessment,MemoryComplaints,BehavioralProblems,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
0,4751,73,Male,Caucasian,22.927749,No,13.297218,6.327112,1.347214,9.025679,...,No,6.518877,No,No,No,No,No,Yes,No,No
1,4752,89,Male,Caucasian,26.827681,No,4.542524,7.619885,0.518767,7.151293,...,No,7.118696,No,No,No,No,No,No,Yes,No
2,4753,73,Male,Other,17.795882,No,19.555085,7.844988,1.826335,9.673574,...,No,5.895077,No,No,No,Yes,No,Yes,No,No
3,4754,74,Female,Caucasian,33.800817,Yes,12.209266,8.428001,7.435604,8.392554,...,No,8.965106,No,Yes,No,No,No,No,No,No
4,4755,89,Male,Caucasian,20.716974,No,18.454356,6.310461,0.795498,5.597238,...,No,6.045039,No,No,No,No,Yes,Yes,No,No

In [16]:
# Export CSV for tableau purposes
df.to_csv('../Resources/tableau_alzheimers_disease_data.csv')